name: 'Create Database Branch'
description: 'Creates a branch for a PlanetScale database.'
inputs:
  database_name:
    description: 'The name of the database'
    required: true
  branch_name:
    description: 'The name of the new branch'
    required: true
  org_name:
    description: 'The name of the organization that owns the database'
    required: true
  source_branch:
    description: 'The production branch to create the new branch from. Defaults to the default production branch.'
    required: false
  restore_from:
    description: 'The ID of the backup you wish to restore into the new branch.'
    required: false
  region:
    description: 'The region where the new branch should be created. Defaults to the region of the source branch.'
    required: false
  generate_credentials:
    description: 'If true, the action will generate credentials and set them in the respective outputs.'
    required: false
outputs:
  password_name:
    description: 'If `generate_credentials` is set, will contain the name generated for the credentials in the format of "gha<<UNIX_TIMESTAMP>>".'
  username:
    description: 'If `generate_credentials` is set, will contain the username for the branch.'
  password:
    description: 'If `generate_credentials` is set, will contain the password for the branch.'
  hostname:
    description: 'If `generate_credentials` is set, will contain the hostname for the branch.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.database_name }}
    - ${{ inputs.branch_name }}
    - ${{ inputs.org_name }}
    - ${{ inputs.source_branch }}
    - ${{ inputs.restore_from }}
    - ${{ inputs.region }}
    - ${{ inputs.generate_credentials }}