name: 'Hello new branch!'
description: 'Make a branch'
inputs:
  database_name:  # id of input
    description: 'The name of the database'
    required: true
  branch_name:
    description: 'The name of the new branch'
    required: true
  org_name:
    description: 'The name of the organization that owns the database'
    required: true
  source_branch:
    description: 'The production branch to create the new branch from. Defaults to the default production branch.'
    required: false
  restore_from:
    description: 'The ID of the backup you wish to restore into the new branch.'
    required: false
  region:
    description: 'The region where the new branch should be created. Defaults to the region of the source branch.'
    required: false
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.database_name }}
    - ${{ inputs.branch_name }}
    - ${{ inputs.org_name }}
    - ${{ inputs.source_branch }}